# Generated by Django 5.0.6 on 2024-06-11 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientData',
            new_name='Patient',
        ),
    ]
